#pragma once
#include "ReflectObject.h"

namespace ke
{
	REFLECT_OBJECT_CLASS(RenderTargetFormats)
	{
	public:
		REFLECT_OBJECT_CONSTRUCTOR(RenderTargetFormats);

	public:
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _numRenderTargets, 0);
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _rtvFormat0, 0);
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _rtvFormat1, 0);
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _rtvFormat2, 0);
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _rtvFormat3, 0);
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _rtvFormat4, 0);
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _rtvFormat5, 0);
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _rtvFormat6, 0);
		DECLARE_REFLECT_PROPERTY_WITH_DEFAULT(uint8, _rtvFormat7, 0);
	};
}
